### ISSUE TITLE
teachcode - reinforcing coding foundations

### ISSUE THREAD

**Issue by jamesgeorge007** [EddieJaoudeCommunity/support#18]
`teachcode` is a utility by which one can brush up their programming skills right from the terminal. Presently there are 2 learning tracks (Python & JavaScript) comprising 30 tasks. The good thing is that after completing a task the respective solution is pushed to his/her remote repository on GitHub - tracking user progress.

- GitHub Repository: https://github.com/madlabsinc/teachcode
- Docs: https://teachcode.madlabs.xyz/

This is one of the queries often asked about teachcode: https://github.com/madlabsinc/teachcode/issues/73

**Comment by mikeysan** [comment]
Hmm... this sounds interesting. I'll take a look and give some feedback here when I am done.

**Comment by mikeysan** [comment]
I like the idea of this tool and its potential. I wasn't able to use, however, because when I went to install it, I got:
`npm --version
zsh: command not found: npm
`
I'm currently learning Python so I have no need, at least for now, to install node.js on my system. I think the readme could do with an update on where to get the npm tool from for Windows and Mac OS at least.

Personally, I would prefer a docker image to setting up a Javascript developer environment just to test a tool.

**Comment by mikeysan** [comment]
The next thing I noticed is the requirement of users to have access to Github.

If you are targetting new developers, I would propose you consider removing this requirement. Github is not the easiest thing to wrap your head around when you first start learning a programming language.

**Comment by eddiejaoude** [comment]
Hi, I will be reviewing open source projects on a live stream today at 2pm UK time (2.5 hours from now). 

Here is the YouTube live link https://www.youtube.com/watch?v=LyTUj6YQoBo
