### ISSUE TITLE
Project and profile review for YouTube video

### ISSUE THREAD

**Issue by garimasingh128** [EddieJaoudeCommunity/support#417]
Items we can review on a live stream:

GitHub profile https://github.com/garimasingh128

Open source project : https://gitsetgo.netlify.app
Repository link: https://github.com/garimasingh128/gitsetgo

Portfolio: http://garimasingh.me/

Blog: https://garimasingh.netlify.app

**Comment by eddiejaoude** [comment]
Thank you for sharing, I look forward to reviewing 👍

**Comment by Vyvy-vi** [comment]
A few thoughts on the OpenSource Project:
- The design looks great 👍 
- Functionality of site is good, though a few fixes needed:
   1- the location symbol would look much rather effective if it uses the default GitHub location/ the generic location icon:
   2- The `Organisations` section lists the `company` field rather than the GitHub organisations, one is a part of. (might be confusing for a few people)
- The repo is well-made and looks amazing(would be nice if you link your [repo](https://github.com/garimasingh128/gitsetgo) in the issue as well)
The output:
![Screenshot 2020-11-19 at 11 49 12 PM](https://user-images.githubusercontent.com/62864373/99706994-dd9c6100-2ac1-11eb-9609-c0a86d68e97b.png)
My fields in profile:
![Screenshot 2020-11-19 at 11 50 01 PM](https://user-images.githubusercontent.com/62864373/99707065-fa389900-2ac1-11eb-89f8-6b511a7113d9.png)

**Comment by eddiejaoude** [comment]
Its great the community getting involved and supporting each other ❤️

**Comment by eddiejaoude** [comment]
Thank you for sharing this awesome project 👍 . I reviewed it for my YouTube video, it looks really good 🤓 

Some small suggestions:

- Create releases
- Add build command from `package.json` to GitHub Action
- Move `pull_request_template.md` to `.github` folder
- Commits to follow a standard, for example like `Conventional changeling` style
- README is great, but soon it might be worth splitting some of it out into a `docs/` folder with links from the README
- Issue labels are not consistent, some are with capitals, some are with spaces and others with `_`
-

**Comment by garimasingh128** [comment]
Thanks @eddiejaoude I have corrected most of these now and created issues for the others. Your review and advice means a lot. Thanks.

**Comment by eddiejaoude** [comment]
You are welcome @garimasingh128 . The video is being edited today, so should be out this week (hopefully mid week)

**Comment by eddiejaoude** [comment]
Video is live https://www.youtube.com/watch?v=braWUyC77z4&feature=youtu.be

**Comment by garimasingh128** [comment]
Loved the feedback!

**Comment by eddiejaoude** [comment]
Thank you @garimasingh128
