### ISSUE TITLE
[Project Review]: This a project me and my friend made for our college submission

### ISSUE THREAD

**Issue by dheerajdlalwani** [EddieJaoudeCommunity/support#436]
Items we can review on a live stream:

- Open source project

### Technologies used:
- Django
- TailwindCSS
- Javascript

### Hosted on: https://equipstat.herokuapp.com

You may use dummy details to register on the site.

Because of the limited time, we couldn't make it responsive. But apart from that if you could review it and give me any suggestions/advice it would really mean a lot to me.

**Comment by eddiejaoude** [comment]
Initial feedback...

- use Issues
- use Pull Requests 
- use Actions for linting or similar even if there are no automated tests
- keep file/folder naming consistent, this one stands out `EquipStat_WebStore`
- README to have quickstart, requirements etc
- add Code of Conduct

**Comment by dheerajdlalwani** [comment]
Sure! I will look into it right away.

**Comment by mikeysan** [comment]
I love the colour scheme and simplicity. The layout is also very pleasing. 

Here are is my feedback on possible improvements.

I took my test to the hosted site instead of github. A few things I would question or change. I admit they could subject to location and target market but here goes.

1. Filling in the registration form requires that I give you my phone number. I'm not comfortable with that and will likely give you a fake one. (yes, I know this was a test.

![phone_number_is_mandatory](https://user-images.githubusercontent.com/13338176/99279008-a743b500-2827-11eb-819a-0bbed8f1c4c6.PNG)

2. Some products require that I call the seller or email them, while some have (what I expected) an "add to cart" button.
2b. When you click on "contact" it actually tries to open a call app. Thankfully, I tested on my desktop, so no app opened and I had the chance to cancel that action :)

![contact_wants_to_cantact](https://user-images.githubusercontent.com/13338176/99279302-fee22080-2827-11eb-85fd-07bb51c6bbfb.PNG)

2c. I moused over the 'contact' to see what it was trying to do and noticed a 'tel:######'
![mouseOver_contact](https://user-images.githubusercontent.com/13338176/99279423-20430c80-2828-11eb-9beb-9f9b9361783d.PNG)

3. Some allignment on the products page seem a bit off to me.

![text_allignment](https://user-images.githubusercontent.com/13338176/99279546-3f419e80-2828-11eb-8a24-b3c58cc7ed15.PNG)

4. The home page didn't display well on my phone (yes, I switched to my phone to see what it would look like).
![WhatsApp Image 2020-11-16 at 16 27 58](https://user-images.githubusercontent.com/13338176/99280503-5208a300-2829-11eb-9d0e-ab1361842155.jpeg)


I hope these help.

**Comment by dheerajdlalwani** [comment]
Thank you so much @mikeysan for all these reviews.

- Yes there are **2** kinds of products.

  - So the ones which have an add to cart feature, are new products which we the owners of the site plan to sell. So they will be transacting with us. (Store page)

  - the other type is the refurbished products. So, you as an account holder can enlist the products you wish to sell and we will display them as listings. (Refurbished page) In that case, you have to directly contact the seller and we are just here to present you with the listing.

- About the telephone link, we thought it would be a cool feature to like allow the user to call the seller at the click of a button.  We took the idea from google maps app which allows you to call directly. Is that like a bad choice? Or something which is un expected or bad design?

- Alignment issues and responsiveness we are working on. So thank you for pointing out the issue on Products page.

**Comment by mikeysan** [comment]
Hey @dheerajdlalwani I really like this "...the other type is the refurbished products... In that case, you have to directly contact the seller and we are just here to present you with the listing..." idea. Very good idea.

I'm not a product architect by any means, but thinking as a buyer, I wouldn't really want to call someone I don't know about buying a product I saw on a website. The reason it works for Google maps is because you are more likely calling a business to get directions or ask about opening times.

To your question about bad choice or bad design, I would say no. It is NOT a bad design or choice. It is simply a design choice that has to be weighed against a pros and cons list. That list will ultimately also have to rely on your target market. If your tarket market expects to be able to simply click a button and call someone, then I would go in that direction. The only thing I would add is the abilty for those who visit the site from a desktop to see the number and then call.

Another feature you could add is the ability to chat to the seller via the site directly. If user and seller decide to take the conversation off the site, then that's their decision.

What do you think?

**Comment by dheerajdlalwani** [comment]
Yes. The chat feature could be a better idea. Infact I had thought about it but due to limited experience I decided as of now to I'll keep the number.
Can you raise that as an issue? 

And yes I will make it such that the user can see the phone number before calling.

**Comment by eddiejaoude** [comment]
Great team work everyone 💪

**Comment by eddiejaoude** [comment]
@dheerajdlalwani I was going to review for a video I am recording but the repo is 404?

**Comment by dheerajdlalwani** [comment]
I don't know what happened...
Just let me take a look...

**Comment by dheerajdlalwani** [comment]
My other collaborator had made it private... 🤦🏻‍♂️
I've made it public again... Do let me know if it works...
https://github.com/EquipstatTSEC/webstore

**Comment by eddiejaoude** [comment]
Seems to work now. The video is recorded and currently being edited. I will review it in the next video / live stream I do for reviewing open source projects

**Comment by eddiejaoude** [comment]
Reviewed in a live stream https://youtu.be/_JjV9n-G-p0

Looks great, some feedback
- Be consistent with the naming convention of the folders
- No recent commits
- No tags/releases taken yet
- Maybe use labels on the issues
- PRs only by a bot at the moment
- Screenshots are great, but maybe too many images - suggest animated gif or YouTube video
- Code of conduct would be great https://github.com/EquipstatTSEC/webstore/community
