### ISSUE TITLE
Please review my open source project: tkeron

### ISSUE THREAD

**Issue by lemaguilera** [EddieJaoudeCommunity/support#456]
Hello! This is my first open source project and I'm sure it has a lot to improve on the github platform.
This project is used to program web interfaces with components in typescript without the need for extra configurations, just install and start programming.

Items we can review on a live stream:

- Open source project: [tkeron](https://github.com/tkeron/tkeron)

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by eddiejaoude** [comment]
Thank you for sharing your open source project 👍 - I will review it in one of my next videos / live streams 🤓

**Comment by lemaguilera** [comment]
awesome! thanks

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://youtu.be/_JjV9n-G-p0

Looks good, here are some suggestions
- Create tag/release
- Use Issues so that people can discover the project on GitHub get involved in the conversion 
- Use GitHub Action to run `build` command to check project builds correctly
- Add a code of conduct and contributors file https://github.com/tkeron/tkeron/community
