### ISSUE TITLE
What is the git .ignore file used for?

### ISSUE THREAD

**Issue by mohit01-beep** [EddieJaoudeCommunity/support#46]
**Description**

A brief description of the question or issue:

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieJoaude Comminity [here](https://github.com/EddieJaoudeCommunity)

**Comment by NathanDennis** [comment]
A `.gitignore` file inside of the root directory of your project, will contain a list of files and folders that you **don't** want to be uploaded to your GitHub repository when you use `git push` or upload it with the GitHub Desktop app.

An example of  a smaller .gitignore file might look like this:

```
node_modules
.env

# local env files
.env.local
.env.*.local
```

Where `node_modules` (if it's a NodeJS project) is important because you don't want tens of thousands of files in your node_modules folder to be uploaded, and `.env` is also **very** important not to upload because that file usually contains sensitive information, such as API keys and Auth tokens for example.

**Comment by mohit01-beep** [comment]
So if someone download that REPOSITORY and try to run it, it  works properly but they can't see sensitive information which we include in Git.ignore file, Right?

**Comment by jatin2003** [comment]
A `. gitignore` file is a plain text file where you can list out your files/directories to be ignored from being committed or pushed to your remote repo. 

You can also refer to this post by freecodecamp - [Gitignore Explained: What is Gitignore and How to Add it to Your Repo](https://www.freecodecamp.org/news/gitignore-what-is-it-and-how-to-add-to-repo/)

**Comment by jatin2003** [comment]
> So if someone download that REPOSITORY and try to run it, it works properly but they can't see sensitive information which we include in Git.ignore file, Right?

Yeah! So, You might have a file like `.env` which might contain sensitive information like your private API keys or something like that. So, by listing that file in `. gitignore` is going to prevent it from being committed or pushed to GitHub where people might use your private stuff with malicious intent.

**Comment by mohit01-beep** [comment]
oh i got it, thanks @jatin2003
