### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by venukalam** [EddieJaoudeCommunity/support#545]
Please invite me to the GitHub Community Organisation. 

- #### Name: venu kalam

- #### Discord Username(if exists): 

- #### Additional Context:
 I found eddie on youtube (freecodecamp channel)

 I think this is one great way to learn new stuff and improve your network.

:nerd_face:

**Comment by eddiejaoude** [comment]
**Invitation sent for the GitHub Organisation. Welcome to the community** 🎉

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practising:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions on how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps

**Comment by OmkarPh** [comment]
Hi @eddiejaoude 
Can you send me an invitation too..

**Comment by Vyvy-vi** [comment]
@OmkarPh Maybe you could open a new issue for an invitation request on [EddieJaoude/support/invite-me](https://github.com/EddieJaoudeCommunity/support/issues/new?assignees=eddiejaoude%2C+mikeysan&labels=invite+me+to+the+organisation&template=invitation.md&title=Please+invite+me+to+the+GitHub+Community+Organization) ?
That might be faster since Eddie gets a lot of github notifications, and this might not get noticed by them...

:)

**Comment by OmkarPh** [comment]
Ohh fine ✌️
