### ISSUE TITLE
The choice of a community platform

### ISSUE THREAD

**Issue by DoomHammer** [EddieJaoudeCommunity/support#59]
**Description**

I have a question as I'm interested in community-building and the vast amount of tools does not make the choice any easier. For IM chat, the two main platforms I see utilized are Slack and Discord. Sometimes, Telegram is used for this purpose as well.

What are some of your reasons for going with Discord?

**Comment by jatin2003** [comment]
I'm using [**Discord**](https://discord.com/) for building **devcord** a friendly community for developers & I chose Discord as a community platform due to various awesome options it provides us with.

- Unlimited Text & Voice Channels
- Reaction Roles
- Voice Chat
- Streaming (Twitch Replacement)

I think Slack is definitely shifted to be less useful for communities by comparison to what I see here on Discord.

In Discord, I really like that all channels are visible and organized for a new user, and then they can mute ones they're not interested in.

You can also have a look at these posts to get a better idea:-

- https://www.christopherbiscardi.com/why-use-discord-for-open-communities
- https://www.swyx.io/writing/slack-fumble/

You can also join us on **[Devcord](https://discord.com/invite/kC8nxqK)**.

**Comment by eddiejaoude** [comment]
> I think Slack is definitely shifted to be less useful for communities by comparison to what I see here on Discord

So true! Especially with the Slack wysiwyg feature that is really annoying for techies - it is not possible to turn it off at the moment 

> You can also join us on Devcord.

I joined 👍 

## Discord > Slack

I think the only 2 things missing are `deep linking` and maybe `threads`, but I can live without those

For my clients I use Slack, and for communities I have moved them from Slack to Discord, I dont regret it, actually I wish I did it sooner as it seems more community feature focused, where Slack seems more "middle management" focused 😞

**Comment by jatin2003** [comment]
> I think the only 2 things missing are deep linking and maybe threads, but I can live without those

https://www.reddit.com/r/discordapp/comments/hzobo2/threads_are_being_tested/

I'm not sure that threads are going to be implemented or not but I'm damn sure It's gonna take Discord to the next level :)

**Comment by stemount** [comment]
This looks pretty comprehensively answered to me.

> > I think the only 2 things missing are deep linking and maybe threads, but I can live without those
> 
> https://www.reddit.com/r/discordapp/comments/hzobo2/threads_are_being_tested/
> 
> I'm not sure that threads are going to be implemented or not but I'm damn sure It's gonna take Discord to the next level :)

Yes, Threads are a Slack feature that I really like but MS Teams and Google Chat's (identical) threading functionalities are actually great for this sort of thing.

Slack completely destroyed the old WYSIWYG for code snippets etc now a bit of a nightmare, I actually feel more restricted in Slack.

Closing issue
