### ISSUE TITLE
What is DevRel?

### ISSUE THREAD

**Issue by AllanRegush** [EddieJaoudeCommunity/support#64]
**Description**

What is DevRel? 

I've read some answers on google ie. https://devrel.co/about/

Is it really just marketing?

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieJoaude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by eddiejaoude** [comment]
> Is it really just marketing?

"just marketing" 😱 - its engineering and marketing, so twice the work 😉 

I think it is about engineering and the community. I believe we are all a little bit in DevRel, because we use Twitter, Discord and GitHub itself is "Social Coding".

I am recording a video with the DevRel community from http://flyless.dev this coming Wednesday

**Comment by jatin2003** [comment]
As @eddiejaoude said It's much more than marketing as Engaging with the community on various social platforms is also a part.

You can also have a look at this youtube video by James Q Quick to get more insights on the same.

https://www.youtube.com/watch?v=tXQXYCKNA4M&t=15s

**Comment by stemount** [comment]
@AllanRegush DevRel is (generally) developer relations for a company (or maybe represent a handful of companies) e.g. X company has an API, an SDK, some useful data to consume, maybe even provides services for the general public.

**Some related issue titles:**
What is DevRel and what do they do?
What does devrel do day today?
Do I need to be able to code to be devrel?

If you have a SaaS company, a data brokerage company, something where developers need to really have the ultimate say on the integration, a **good Dev Rel** will:
- Work with that company to ensure their APIs are well documented.
- Know enough about how to code. It is not a prerequisite for devrel to code day to day, but if the DevRel person cannot translate what their customers (and their software engineers) are asking for because they don't understand the technology, then they do not provide the valid feedback loop e.g.
  - The API is too hard to understand
  - The API is not performant enough
  - The API does not actually have Y feature which is very important to customer X.
  - Customers do not find value in Z.
  - Company provides a PHP SDK only and the customers use Node.js.
- **Promote the offering** to RELEVANT customers (this is the "is it just an extension of the marketing team" question) at Hackathons.
- **Be a pillar of the community** Attend conferences, hackathons, online communities and be a useful addition to the development world, NOT just promote the wares of their employer.
- **Provide a level of confidence during due diligence** A CTO, technical architect or even an uninformed startup founder should always do their due dil on companies they work with as there are many bold claims made by companies for technologies they do not have. Customers may have been burned before and found there to be no support.
- **Promote contributing to open source with their $$$** If a DevRel's company has a tech budget and profits from open source, the DevRel should definitely wager that their employer fund the projects that their software depends on.

**Comment by AllanRegush** [comment]
Thank you all for your replies. I'll close this issue.
