### ISSUE TITLE
I have this error in Android Studio "Unable to detect adb version, exit value: 0xc000007b"

### ISSUE THREAD

**Issue by mohit01-beep** [EddieJaoudeCommunity/support#70]
**Description**

I installed Android Studio many times but every time their was Gradle dependencies error came, somehow  today i removed that error but then this error came

**Stack**

Project of Kotlin/java 

**Working Environment**

Windows

Browser:

Laptop 

**Screenshots**

![android](https://user-images.githubusercontent.com/59441111/90394407-3c5fd200-e0b0-11ea-8ee4-8d44c36e4b69.png)

[Optional] **Additional Context**

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieJoaude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by BOLT04** [comment]
Hi @mohit01-beep, that might be because you don't have any devices created:
![image](https://user-images.githubusercontent.com/18630253/90442066-ee5bc600-e0d1-11ea-956b-27f0da3dd64f.png)

Check out [these docs](https://developer.android.com/studio/run/managing-avds) in order to create a device, and see if those event logs keep happening.

**Comment by stemount** [comment]
<img width="555" alt="image" src="https://user-images.githubusercontent.com/150512/91728294-cde43f00-eb9a-11ea-8ce9-04ac8cda6b48.png">

@mohit01-beep I pinched this from a youtube video as something to try!

owever I suspect that (for some reason) your `adb` installation is broken, not in your system path, or even the Android Studio needs configuring for ADB usage.

If you do to "Terminal" at the bottom and type `adb devices list` do you see anything
