### ISSUE TITLE
Trying to find an open source project, specifically Front-end development

### ISSUE THREAD

**Issue by JoelAngels** [EddieJaoudeCommunity/support#76]
**Description**

A brief description of the question or issue:

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieJoaude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by JoelAngels** [comment]
Have an Idea let me know!

**Comment by eddiejaoude** [comment]
What technologies do you use?

We are a few frontend projects starting up if you want to join in:
- Map project (display where people on the live stream are) https://github.com/EddieJaoudeCommunity/EddieBotMap
- Website (we have not started yet, probably be html, css, tailwind for now)
- EddieBot UI (not much movement on this at the moment)

On the website we will list these and their technologies so it is clearer for people. You join at an interesting time, because it is so early on, you can help shape the community with us 🤓

**Comment by JoelAngels** [comment]
Hey,
The technologies I use are HTML / CSS and javascript but am still learning
to great and comfortable with them as well as React
I would really want to be a part of this BTW,
I can definitely contribute on the website side, but for the rest, I need
to learn typescript to be able to discord project with you guys.
It is gonna take me some time but it's worth it.

**Comment by eddiejaoude** [comment]
We are all still learning so dont worry, it is part of the fun 🤓 - we will all figure it out together 💪

**Comment by stemount** [comment]
@JoelAngels I think this ticket has been resolved as this community already has some pretty funky stuff.

Definitely brush up on TailwindCSS for a framework as you are "actually using CSS properties" even when you use a utility framework.

Closing issue 💯

**Comment by eddiejaoude** [comment]
@JoelAngels  Since this ticket was created, we have started work on the community website. Like @stemount says it is tailwind focused for now https://github.com/EddieJaoudeCommunity/EddieJaoudeCommunity.github.io
