### ISSUE TITLE
Request to join the community? :)

### ISSUE THREAD

**Issue by rperry99** [EddieJaoudeCommunity/support#90]
Hello! Would I be able to join this community? 😄  I am trying to make open source a much bigger part of my coding career!

Thanks in advance!

**Comment by eddiejaoude** [comment]
Of course @rperry99 , great to have you part of our community 🎉 

I have sent the invitation to our organisation. After you accept, you will need to find your name in the list of people and make it public if you want it to appear on your GitHub profile for everyone to see, only you can change the visibility https://github.com/orgs/EddieJaoudeCommunity/people

**Comment by rperry99** [comment]
Thanks @eddiejaoude !

**Comment by BOLT04** [comment]
Hey @rperry99, love the enthusiasm 😃 💯💯 ! Contributing to open source helps your career for sure, since you collaborate with tons of people.
Welcome to the community 🎉 and if you are interested in more of a front-end project, take a look at our [community website repo](https://github.com/EddieJaoudeCommunity/EddieJaoudeCommunity.github.io). Any contribution is very welcome 👍 .
